name: CI
on: push

jobs: 
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v3
      - name: Gradle build
        run: ./ci/build-app.sh
      - name: Test
        run: ./ci/unit-test-app.sh
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: ./app/build/libs/app-0.1-all.jar
  Containerize:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    env:
      docker_password: ${{ SECRETS.GITHUB_TOKEN }}
      GIT_COMMIT: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: Fetch build artifact
        uses: actions/download-artifact@v3
        with:
          name: java-app
          path: ./app/build/libs/app-0.1-all.jar
      - name: set lower case owner name
        run: |
          echo "ACTOR_LC=${docker_username,,}" >>${GITHUB_ENV}
      - name: Build Docker Image
        run: ./ci/build-docker.sh
        env:
          docker_username: ${{ env.ACTOR_LC }}
      - name: Publish Docker Image
        run: ./ci/push-docker.sh
        env:
          docker_username: ${{ env.ACTOR_LC }}
      