name: CI
on: push

env:
  docker_username: magnushjensen

jobs: 
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v3
      - name: Gradle build
        run: ./ci/build-app.sh
      - name: Test
        run: ./ci/unit-test-app.sh
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: ./app/build/libs/app-0.1-all.jar
  Containerize:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    env:
      docker_password: ${{ SECRETS.GITHUB_TOKEN }}
      GIT_COMMIT: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: Fetch build artifact
        uses: actions/download-artifact@v3
        with:
          name: java-app
          path: ./app/build/libs/app-0.1-all.jar
      - name: Build Docker Image
        run: ./ci/build-docker.sh
      - name: Publish Docker Image
        run: ./ci/push-docker.sh
  component-test:
    name: Component Test
    runs-on: ubuntu-latest
    needs: [Containerize]
    steps:
      - uses: action/checkout@v3
      - name: Execute component test
        run: ./ci/component-test.sh
  performance-test:
    name: Performance Test
    runs-on: ubuntu-latest
    needs: [Containerize]
    steps:
      - uses: action/checkout@v3
      - name: Execute perforamcne test
        run: ./ci/performance-test.sh